server:
  port: ${PORT:8080}
eureka:
  client:
    service-url:
      defaultZone: eureka-service:8761/eureka
spring:
  jpa:
    deferDatasourceInitialization: true
    hibernate:
      ddlAuto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/parcialservicio1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver